---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSources:
    dataSource:
        dialect: net.kaleidos.hibernate.PostgresqlExtensionsDialect
        driverClassName: org.postgresql.Driver
        username: nucleus
        password: nucleus
        url: jdbc:postgresql://localhost:5432/nucleus
        dbCreate: none
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    lookup:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: 
        url: jdbc:mysql://localhost/etv2prod3
        dbCreate: none

environments:
    development:
        dataSources:
            dataSource:
                dbCreate: none
                url: jdbc:postgresql://localhost:5432/nucleus
            lookup:
                dbCreate: none
                url: jdbc:mysql://localhost/etv2prod3
    test:
        dataSources:
            dataSource:
                dbCreate: none
                url: jdbc:postgresql://localhost:5432/nucleus
            lookup:
                dbCreate: none
                url: jdbc:mysql://localhost/etv2prod3
    production:
        dataSources:
            dataSource:
                dbCreate: none
                username: nucleus
                password: nucleus
                url: jdbc:postgresql://gooru-30-prod-postgresdb.c1ybherlivcq.us-west-1.rds.amazonaws.com/;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
                properties:
                    jmxEnabled: true
                    initialSize: 5
                    maxActive: 50
                    minIdle: 5
                    maxIdle: 25
                    maxWait: 10000
                    maxAge: 600000
                    timeBetweenEvictionRunsMillis: 5000
                    minEvictableIdleTimeMillis: 60000
                    validationQuery: SELECT 1
                    validationQueryTimeout: 3
                    validationInterval: 15000
                    testOnBorrow: true
                    testWhileIdle: true
                    testOnReturn: false
                    jdbcInterceptors: ConnectionState
                    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
            lookup:
                dbCreate: none
                username: etv2admin
                password: xjkK6LUuqa83zMeC
                url: jdbc:mysql://etv2prod3-new.cdr3srm8sgkk.us-west-1.rds.amazonaws.com/
                
---
---
grails:
    profile: web
    codegen:
        defaultPackage: et2gooru
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false
      
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
